# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/blueline/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),blueline)

$(call add-radio-file-sha1-checked,radio/abl.img,22bd049f2f51de9bf15d98c2a375b4463f802402)
$(call add-radio-file-sha1-checked,radio/aop.img,f8c47e699c918bcf4b877b365c0ef30f5f0171f9)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,fcd852c89814ad03974873e451ac3592cd4ecaaa)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,db3ddf969e495bc8c2e966e9c8a2af2707b970fd)
$(call add-radio-file-sha1-checked,radio/devcfg.img,4deff192825605b10e86345477dbd2874acee3f1)
$(call add-radio-file-sha1-checked,radio/hyp.img,4ec7f4772bbfe2c98a5ee903e3b46cf02eeb9906)
$(call add-radio-file-sha1-checked,radio/keymaster.img,447c41fbf8819b88354bb952e870763bee25c22b)
$(call add-radio-file-sha1-checked,radio/modem.img,300e36685adf99fe8a330ba3827d6f9565425a72)
$(call add-radio-file-sha1-checked,radio/qupfw.img,e086cf7cb6ec0770b63b2f19e40686616ed3f2f1)
$(call add-radio-file-sha1-checked,radio/tz.img,ee6ffe9908597867b6081fb0349f7762cfb29d16)
$(call add-radio-file-sha1-checked,radio/xbl.img,4fc8ba1428858abdae21c4c222e12274e492e46b)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,8e2e008a4b5d7b5d6a3e0fd6f9b8be994cb35f3c)

endif
