# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/blueline/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),blueline)

$(call add-radio-file,radio/abl.img)
$(call add-radio-file,radio/aop.img)
$(call add-radio-file,radio/cmnlib.img)
$(call add-radio-file,radio/cmnlib64.img)
$(call add-radio-file,radio/devcfg.img)
$(call add-radio-file,radio/hyp.img)
$(call add-radio-file,radio/keymaster.img)
$(call add-radio-file,radio/modem.img)
$(call add-radio-file,radio/qupfw.img)
$(call add-radio-file,radio/tz.img)
$(call add-radio-file,radio/xbl.img)
$(call add-radio-file,radio/xbl_config.img)

endif
